## lesson2-numpy(1)

In [1]:
import numpy as np

In [2]:
a=np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b=np.arange(48).reshape(3,4,4)#三维数组

In [13]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [14]:
a=np.array([[1,2,3],[5,6,7]])#列表嵌套列表，二维数组

In [15]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
a.ndim#两维

2

In [17]:
a.shape

(2, 3)

In [18]:
b=np.zeros(9)

In [19]:
b

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [20]:
b.dtype#数据类型

dtype('float64')

In [21]:
b.astype('int32')#转变数据类型

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
c=np.arange(10)

In [25]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
c[5:8]

array([5, 6, 7])

In [27]:
c[5:8]=100#给5，6，7位赋值

In [28]:
c

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [29]:
d=c[5:8].copy()#复制

In [30]:
d

array([100, 100, 100])

In [31]:
a=np.arange(24).reshape(2,3,4)

In [32]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a[0][0]

array([0, 1, 2, 3])

In [36]:
a[0][0][0]#连续切

0

In [37]:
a=np.random.randn(3,4)#正态分布随机数

In [38]:
a

array([[ 1.7342851 , -0.32404189, -1.73016079, -0.62095682],
       [-1.14002352,  0.43466436, -1.36888499,  1.75897401],
       [-2.45951858, -0.26838532,  0.52725212,  0.02630481]])

In [41]:
a>0

array([[ True, False, False, False],
       [False,  True, False,  True],
       [False, False,  True,  True]], dtype=bool)

In [42]:
a[a>0]#布尔型索引

array([ 1.7342851 ,  0.43466436,  1.75897401,  0.52725212,  0.02630481])

In [43]:
a[a<0]=0#布尔型索引赋值

In [44]:
a

array([[ 1.7342851 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.43466436,  0.        ,  1.75897401],
       [ 0.        ,  0.        ,  0.52725212,  0.02630481]])

In [52]:
a=np.random.normal(size=(3,4))#标准正态分布随机数,定义参数size

In [53]:
a

array([[-0.58616438,  1.00819678, -1.13333951,  2.20315262],
       [ 0.34891875, -0.54123595,  0.92666668,  1.67857563],
       [ 0.37915182,  0.01610758,  0.38820793, -0.49058031]])

In [54]:
a=np.random.randint(1,5,(3,4))#参数low,high,size,前包括后不包括

In [55]:
a

array([[2, 3, 4, 2],
       [2, 3, 2, 1],
       [3, 1, 3, 2]])

## lesson3-numpy(2)

In [56]:
import numpy as np

In [58]:
a=np.arange(10).reshape(2,5)

In [59]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
a.T#转置

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [64]:
#数组的运算，广播的特性
a*10

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [65]:
a+a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [67]:
np.sqrt(a)#平方根

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ]])

In [68]:
np.abs(a)#绝对值

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
np.sum(a)

45

In [76]:
a.sum()

45

In [72]:
b=np.arange(10,0,-1).reshape(2,5)#倒序的数组

In [73]:
b

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [74]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
np.maximum(a,b)#数组中的元素逐一比对

array([[10,  9,  8,  7,  6],
       [ 5,  6,  7,  8,  9]])

In [78]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
a.sum(axis=1)#改行的：列与列之间进行相加

array([10, 35])

In [80]:
a.sum(axis=0)#该列的 ：行与行之间进行相加

array([ 5,  7,  9, 11, 13])

In [81]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
a.cumsum()#累加

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [86]:
b.cumprod()#累乘

array([     10,      90,     720,    5040,   30240,  151200,  604800,
       1814400, 3628800, 3628800], dtype=int32)

** 布尔值也可以做累加，累乘 **

In [87]:
c=np.array([True,False,True,False,True,True,False])

In [88]:
c

array([ True, False,  True, False,  True,  True, False], dtype=bool)

In [89]:
c.sum()

4

In [90]:
d=np.random.randn(2,5)#正态随机数

In [93]:
np.sort(d)#排序，默认由最小到最大

array([[-0.68087498, -0.46480061,  0.4840063 ,  0.65210421,  1.14960957],
       [-2.56647377, -1.43512728,  0.31562676,  0.63431248,  0.97915227]])

** 条件逻辑运算 **

In [97]:
cond=np.array([True,False,True,True,False])#定义条件
X=np.array([1,3,5,8,9])
Y=np.array([22,23,26,28,29])

In [98]:
e=np.where(cond,X,Y)#条件判断np.where，True用X的值，False用Y的值

In [99]:
e

array([ 1, 23,  5,  8, 29])

In [100]:
#纯python的列表推导会很慢
[(x if c else y) for x,y,c in zip(X,Y,cond)]

[1, 23, 5, 8, 29]

In [103]:
np.unique(a)#唯一值 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a.max()

9

In [107]:
a.min()

0

In [108]:
np.save('网易numpy练习',a)#保存

In [111]:
np.load('网易numpy练习.npy')#读取

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])