In [1]:
"""随机森林算法的优点
一、回归、分类都适用 
二、输入特征的重要性
三、易使用、参数少直观
四、不易过拟合
五、对于分布不均的数据也能很好地predict"""

'随机森林算法的优点\n一、回归、分类都适用 \n二、输入特征的重要性\n三、易使用、参数少直观\n四、不易过拟合\n五、对于分布不均的数据也能很好地predict'

集合算法（bagging算法） ：有放回采样，n个子样本分别建立模型后进行预测，少数服从多数

集合算法的好处：
1、可以有效防止过拟合
2、降低噪声干扰，提高模型准确性和稳定性

### ** 随机抽取一部分特征、随机抽取一部分数据进行训练 **

In [2]:
"""参数：
决策树的个数t
构建单棵决策树使用的特征数量"""

'参数：\n决策树的个数t\n构建单棵决策树使用的特征数量'

In [3]:
"""随机森林算法
1、采样样本（放回采样）
2、采样特征
3、构建决策树
4、重复t次，构建出t棵决策树
5、综合多棵决策树的预测结果，作为随机森林的预测结果。
回归问题：平均值   分类问题：少数服从多数"""

'随机森林算法\n1、采样样本（放回采样）\n2、采样特征\n3、构建决策树\n4、重复t次，构建出t棵决策树\n5、综合多棵决策树的预测结果，作为随机森林的预测结果。\n回归问题：平均值   分类问题：少数服从多数'

In [4]:
"""采样一部分特征的原因:
确保所有特征都可以对预测结果产生影响（影响特别大的特征会在很多时候不被抽取）"""

'采样一部分特征的原因:\n确保所有特征都可以对预测结果产生影响（影响特别大的特征会在很多时候不被抽取）'

### 计算特征的重要性
#### 通过查看使用该特征减少了森林中所有树多少的不纯度，来衡量特征的重要性。
#### 它在训练后自动计算每个特征的得分，并对结果进行标准化，以使所有特征的重要性总和等于1

* n_estimators 决策树数量
* max_features 单个决策树特征数量
* min_sample_leaf  决定了叶子的数量
* n_jobs 允许使用处理器的数量，若为1就是1个，-1表示无限制

In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('train.csv')

In [7]:
data = data[['Survived', 'Pclass',  'Sex', 'Age', 'SibSp',
       'Parch',  'Fare',  'Embarked']]#Sibsp是否与兄妹同在，Parch是否与父母同在

In [8]:
data['Age'] = data['Age'].fillna(data['Age'].mean())#平均值填充缺失值

In [9]:
data.fillna(0,inplace=True)

In [10]:
data['Sex']=[1 if x=='male' else 0 for x in data.Sex]#列表推导式，也可用 lambda

In [11]:
# 独热编码
data['p1']=np.array(data["Pclass"]==1).astype(np.int32)
data['p2']=np.array(data["Pclass"]==2).astype(np.int32)
data['p3']=np.array(data["Pclass"]==3).astype(np.int32)

In [12]:
del data['Pclass']

In [13]:
data['e1']=np.array(data['Embarked']=='S').astype(np.int32)
data['e2']=np.array(data['Embarked']=='C').astype(np.int32)
data['e3']=np.array(data['Embarked']=='Q').astype(np.int32)

In [14]:
del data['Embarked']

In [15]:
data_train = data[[ 'Sex', 'Age', 'SibSp',
       'Parch',  'Fare', 'p1','p2','p3','e1','e2','e3']].values

In [16]:
# 不牵扯距离的计算，不用标准化
data_target = data['Survived'].values


In [17]:
data_target = data['Survived'].values.reshape(len(data),1)

In [19]:
np.shape(data_train),np.shape(data_target)

((891, 11), (891, 1))

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test = train_test_split(data_train,data_target,test_size=0.2)

In [22]:
x_train.shape,x_test.shape

((712, 11), (179, 11))

In [23]:
# 使用随机森林算法

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
model = RandomForestClassifier(n_estimators=100,n_jobs=2)

In [26]:
model.fit(x_train,y_train.ravel())#ravel使变成一列

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [27]:
y_train# 已经被ravel()方法更改，更改了视图

array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [28]:
model.score(x_test,y_test)

0.83240223463687146

In [29]:
model.feature_importances_

array([ 0.25317705,  0.25685915,  0.04610984,  0.03954629,  0.25246924,
        0.04274197,  0.01635258,  0.04948644,  0.01921136,  0.01407165,
        0.00997443])

In [30]:
for futh,imp in zip([ 'Sex', 'Age', 'SibSp',
       'Parch',  'Fare', 'p1','p2','p3','e1','e2','e3'],model.feature_importances_):
    print(futh,imp)#通过迭代打印特征

Sex 0.253177048499
Age 0.25685914889
SibSp 0.0461098413992
Parch 0.0395462892009
Fare 0.252469238068
p1 0.0427419732753
p2 0.0163525755004
p3 0.0494864448187
e1 0.0192113639646
e2 0.014071646653
e3 0.00997442973062


## 注意这里要reshape(1,-1),([])和([[]])的区别

In [31]:
x_test[0]#一维数组是一列

array([  1.,  52.,   0.,   0.,  13.,   0.,   1.,   0.,   1.,   0.,   0.])

In [32]:
x_test[0].reshape(1,-1)#一行n列

array([[  1.,  52.,   0.,   0.,  13.,   0.,   1.,   0.,   1.,   0.,   0.]])

In [33]:
model.predict(x_test[0].reshape(1,-1))

array([0], dtype=int64)

In [34]:
model.estimators_#打印100个决策树

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=494612695, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=978459108, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weig

In [35]:
from sklearn.model_selection import GridSearchCV#进行循环交叉验证评分

In [36]:
n_estimators = range(80,130)

In [37]:
param_grid = {'n_estimators':n_estimators}#字典形式

In [38]:
model = GridSearchCV(RandomForestClassifier(),param_grid,cv=5)

In [39]:
model.fit(data_train,data_target.ravel())

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': range(80, 130)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [41]:
model.best_params_#82个决策树最好

{'n_estimators': 82}