Sigmoid函数

再用平方差计算损失，他的值非常小，用梯度下降法，力度变得不够

交叉熵

计算交叉熵代码：tf.nn.sparse_softmax_cross_entropy_with_logits

tf.nn.softmax_cross_entropy_with_logits#计算出交叉熵的损失值

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('C:\\Users\\chen jia ni\\Desktop\\train.csv')

In [3]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
data = data[['Survived','Pclass','Sex','Age', 'SibSp', 'Parch','Fare','Embarked']]

In [5]:
data = data.fillna(0)

In [6]:
data['Sex']=pd.factorize(data.Sex)[0]#因子分解，取第一位代表属性,dummy也可以用

In [7]:
data.head()#Plass的1,2,3 数据原始的会给船票等级添加默认线性关系，需做处理

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    0  22.0      1      0   7.2500        S
1         1       1    1  38.0      1      0  71.2833        C
2         1       3    1  26.0      0      0   7.9250        S
3         1       1    1  35.0      1      0  53.1000        S
4         0       3    0  35.0      0      0   8.0500        S

one-hot编码

In [8]:
data['p1'] = np.array(data['Pclass']==1).astype(np.float64)
data['p2'] = np.array(data['Pclass']==2).astype(np.float64)
data['p3'] = np.array(data['Pclass']==3).astype(np.float64)

In [9]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked   p1   p2   p3
0         0       3    0  22.0      1      0   7.2500        S  0.0  0.0  1.0
1         1       1    1  38.0      1      0  71.2833        C  1.0  0.0  0.0
2         1       3    1  26.0      0      0   7.9250        S  0.0  0.0  1.0
3         1       1    1  35.0      1      0  53.1000        S  1.0  0.0  0.0
4         0       3    0  35.0      0      0   8.0500        S  0.0  0.0  1.0

In [10]:
del data['Pclass']

In [11]:
data['e1'] = np.array(data['Embarked']=='S').astype(np.float64)
data['e2'] = np.array(data['Embarked']=='C').astype(np.float64)
data['e3'] = np.array(data['Embarked']=='Q').astype(np.float64)

In [12]:
data.head()

Survived  Sex   Age  SibSp  Parch     Fare Embarked   p1   p2   p3   e1  \
0         0    0  22.0      1      0   7.2500        S  0.0  0.0  1.0  1.0   
1         1    1  38.0      1      0  71.2833        C  1.0  0.0  0.0  0.0   
2         1    1  26.0      0      0   7.9250        S  0.0  0.0  1.0  1.0   
3         1    1  35.0      1      0  53.1000        S  1.0  0.0  0.0  1.0   
4         0    0  35.0      0      0   8.0500        S  0.0  0.0  1.0  1.0   

    e2   e3  
0  0.0  0.0  
1  1.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0

In [13]:
del data['Embarked']

In [14]:
data.columns

Index(['Survived', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'p1', 'p2', 'p3',
       'e1', 'e2', 'e3'],
      dtype='object')

In [15]:
import tensorflow as tf

np.stack#每列数据打包到一列

In [16]:
data_data = np.stack([data.Sex.values.astype(np.float64),data.Age.values.astype(np.float64),data.Parch.values.astype(np.float64),
                    data.Fare.values.astype(np.float64),data.SibSp.values.astype(np.float64),
                    data.e1.values,data.e2.values,data.e3.values,
                    data.p1.values,data.p2.values,data.p3.values])

In [17]:
data_data

array([[  0.,   1.,   1., ...,   1.,   0.,   0.],
       [ 22.,  38.,  26., ...,   0.,  26.,  32.],
       [  0.,   0.,   0., ...,   2.,   0.,   0.],
       ..., 
       [  0.,   1.,   0., ...,   0.,   1.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   1., ...,   1.,   0.,   1.]])

In [18]:
data_data = data_data.T#转置后，array每一列代表特征

In [19]:
data_data

array([[  0.,  22.,   0., ...,   0.,   0.,   1.],
       [  1.,  38.,   0., ...,   1.,   0.,   0.],
       [  1.,  26.,   0., ...,   0.,   0.,   1.],
       ..., 
       [  1.,   0.,   2., ...,   0.,   0.,   1.],
       [  0.,  26.,   0., ...,   1.,   0.,   0.],
       [  0.,  32.,   0., ...,   0.,   0.,   1.]])

In [20]:
data.Survived=data.Survived.values.astype(np.float64)

In [21]:
data.Survived

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
5      0.0
6      0.0
7      0.0
8      1.0
9      1.0
10     1.0
11     1.0
12     0.0
13     0.0
14     0.0
15     1.0
16     0.0
17     1.0
18     0.0
19     1.0
20     0.0
21     1.0
22     1.0
23     1.0
24     0.0
25     1.0
26     0.0
27     0.0
28     1.0
29     0.0
      ... 
861    0.0
862    1.0
863    0.0
864    0.0
865    1.0
866    1.0
867    0.0
868    0.0
869    1.0
870    0.0
871    1.0
872    0.0
873    0.0
874    1.0
875    1.0
876    0.0
877    0.0
878    0.0
879    1.0
880    1.0
881    0.0
882    0.0
883    0.0
884    0.0
885    0.0
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [22]:
data_target = np.reshape(data.Survived.values.astype(np.float64),(891,1))

In [23]:
np.shape(data_target)

(891, 1)

In [24]:
np.shape(data_data)

(891, 11)

以上完成数据整理

In [25]:
data_target

array([[ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
      

## 定义网络

In [26]:
x = tf.placeholder("float",shape=[None,11])
y = tf.placeholder("float",shape=[None,1])

weight权重输入值的行数与x的列数对应，输出值是一个标量

In [27]:
weight = tf.Variable(tf.random_normal([11,1]))#权重
bias = tf.Variable(tf.random_normal([1]))#偏置
output = tf.matmul(x,weight) + bias #matmul矩阵乘法
pred = tf.cast(tf.sigmoid(output)>0.5,tf.float32) #cast改变数值类型，计算概率值sigmoid大于0.5

In [28]:
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels = y,logits=output))#tf.reduce_mean沿着某一维度计算元素的平均值

In [29]:
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss)#梯度下降法,最小化损失函数

In [30]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(pred,y),tf.float32))#布尔值转换为数值，求平均值

进行训练

In [31]:
sess = tf.Session()#初始化创建会话
sess.run(tf.global_variables_initializer())#初始化一个变量

In [32]:
for i in range(10000):#训练1万步
    for n in range(len(data_target)//100):#每100行输入以下值打乱训练数据，增加泛化能力,用目标数据的长度//整除,
        index = np.random.permutation(len(data_target))#乱序
        data_data = data_data[index]#改变data_data顺序
        data_target = data_target[index]#增加泛化能力
        batch_xs = data_data[n:n+100]#每次取出100个值
        batch_ys =data_target[n:n+100]
        sess.run(train_step,feed_dict={x:batch_xs,y:batch_ys})#feed_dict训练
    if i%1000 == 0:
        print(sess.run((loss,accuracy),feed_dict={x:batch_xs,y:batch_ys}))#每隔1000步看loss,accuracy

(2.2305248, 0.37)
(0.67624396, 0.63999999)
(0.56664258, 0.73000002)
(0.54261494, 0.75999999)
(0.48375469, 0.77999997)
(0.46564439, 0.82999998)
(0.51496118, 0.75)
(0.46878663, 0.75999999)
(0.47841939, 0.75999999)
(0.49797314, 0.76999998)


## 评估

test数据集同上,复制train

In [52]:
data_test = pd.read_csv('C:\\Users\\chen jia ni\\Desktop\\test.csv')

In [53]:
data_test = data_test.fillna(0)

In [58]:
data_test = data_test[['Pclass','Sex','Age', 'SibSp', 'Parch','Fare','Embarked']]

In [65]:
data_test['Sex']= pd.factorize(data_test.Sex)[0]
data_test['p1'] = np.array(data_test['Pclass']==1).astype(np.float64)
data_test['p2'] = np.array(data_test['Pclass']==2).astype(np.float64)
data_test['p3'] = np.array(data_test['Pclass']==3).astype(np.float64)
data_test['e1'] = np.array(data_test['Embarked']=='S').astype(np.float64)#船舱位置
data_test['e2'] = np.array(data_test['Embarked']=='C').astype(np.float64)
data_test['e3'] = np.array(data_test['Embarked']=='Q').astype(np.float64)
test_data = np.stack([data_test.Sex.values.astype(np.float64),data_test.Age.values.astype(np.float64),data_test.Parch.values.astype(np.float64),
                    data_test.Fare.values.astype(np.float64),data_test.SibSp.values.astype(np.float64),
                    data_test.e1.values,data_test.e2.values,data_test.e3.values,
                    data_test.p1.values,data_test.p2.values,data_test.p3.values]).T#转置

In [66]:
test_label = pd.read_csv('C:\\Users\\chen jia ni\\Desktop\\gender_submission.csv')#真实预测值结果

In [67]:
test_label = np.reshape(test_label.Survived.values.astype(np.float64),(418,1))#取出真实预测结果

In [68]:
sess.run(accuracy,feed_dict={x:test_data , y:test_label})#评估结果

0.97368419